In [1]:
data_dir = '/Users/jnaiman/Downloads/tmp/JCDL2025/other_datasets/vistext/data/'

In [35]:
import pandas as pd
import json
import numpy as np

In [3]:
df_tr = pd.read_json(data_dir + 'data_train.json')

In [4]:
df_tr.head()

,caption_id,img_id,split,scenegraph,datatable,caption_L1,caption_L2L3,L1_properties
0,101,1,train,title National Football League average ticket ...,National Football League average ticket price ...,National Football League average ticket price ...,The ticket price shown for 2006 is just over 6...,"[line, National Football League average ticket..."
1,201,2,train,title Average viewers of Minecraft on Twitch w...,Average viewers of Minecraft on Twitch worldwi...,This is a area plot titled Average viewers of ...,Viewers of Minecraft on twitch has gradually i...,"[area, Average viewers of Minecraft on Twitch ..."
2,202,2,train,title Average viewers of Minecraft on Twitch w...,Average viewers of Minecraft on Twitch worldwi...,This is a area plot titled Average viewers of ...,Minecraft viewing on Twitch sharply increased ...,"[area, Average viewers of Minecraft on Twitch ..."
3,401,4,train,title Which of the following social and econom...,Which of the following social and economic iss...,This is a bar plot called Which of the followi...,The main issue is finding a job which would fi...,"[bar, Which of the following social and econom..."
4,501,5,train,title Share of prisoners under sentence of dea...,Share of prisoners under sentence of death in ...,This is a bar chart named Share of prisoners u...,Death rates have peaked in pensioners in the U...,"[bar, Share of prisoners under sentence of dea..."

In [6]:
print(df_tr.iloc[0]['scenegraph'])

title National Football League average ticket price from 2006 to 2019 (in U.S. dollars) x 100 y -32 x-axis x 100 y 40.042 Year y-axis x -24 y 100 Ticket price in U.S. dollars xtick x 0 val 2006 x 31 val 2008 x 62 val 2010 x 92 val 2012 x 123 val 2014 x 154 val 2016 x 185 val 2018 ytick y 200 val 0 y 164 val 20 y 127 val 40 y 91 val 60 y 55 val 80 y 18 val 100 marks line XY 0 86.582 desc XY 15.375 77.982 desc XY 30.75 68.727 desc XY 46.167 63.655 desc XY 61.542 60.964 desc XY 76.917 59.382 desc XY 92.291 57.491 desc XY 107.709 51.745 desc XY 123.083 46.491 desc XY 138.458 43.945 desc XY 153.833 30.945 desc XY 184.625 17.709 desc XY 200 13.909 desc

In [21]:
df_tr.iloc[0]['datatable']

'National Football League average ticket price from 2006 to 2019 (in U.S. dollars) <s> Year Ticket price in U.S. dollars Dec 31, 2005 62.38 Dec 31, 2006 67.11 Dec 31, 2007 72.2 Dec 31, 2008 74.99 Dec 31, 2009 76.47 Dec 31, 2010 77.34 Dec 31, 2011 78.38 Dec 31, 2012 81.54 Dec 31, 2013 84.43 Dec 31, 2014 85.83 Dec 31, 2015 92.98 Dec 31, 2017 100.26 Dec 31, 2018 102.35'

In [15]:
n = 596

df_sc = pd.read_json(data_dir + 'scenegraphs/'+str(n)+'.json')

In [9]:
df_sc

,marktype,name,role,interactive,clip,items,zindex
0,group,root,frame,True,False,"{'items': [{'marktype': 'group', 'role': 'axis...",0

In [12]:
df_sc['items'].values[0]

{'items': [{'marktype': 'group',
   'role': 'axis',
   'interactive': False,
   'clip': False,
   'items': [{'items': [{'marktype': 'rule',
       'role': 'axis-grid',
       'interactive': False,
       'clip': False,
       'items': [{'x': 0,
         'y': -200,
         'opacity': 1,
         'stroke': '#888',
         'strokeWidth': 1,
         'y2': 0},
        {'x': 53,
         'y': -200,
         'opacity': 1,
         'stroke': '#888',
         'strokeWidth': 1,
         'y2': 0},
        {'x': 105,
         'y': -200,
         'opacity': 1,
         'stroke': '#888',
         'strokeWidth': 1,
         'y2': 0},
        {'x': 158,
         'y': -200,
         'opacity': 1,
         'stroke': '#888',
         'strokeWidth': 1,
         'y2': 0}],
       'zindex': 0}],
     'x': 0.5,
     'y': 200.5,
     'orient': 'bottom'}],
   'zindex': 0,
   'aria': False},
  {'marktype': 'group',
   'role': 'axis',
   'interactive': False,
   'clip': False,
   'items': [{'items': [{'marktype': 'rule',
       'role': 'axis-grid',
       'interactive': False,
       'clip': False,
       'items': [{'x': 0,
         'y': 200,
         'opacity': 1,
         'stroke': '#888',
         'strokeWidth': 1,
         'x2': 200},
        {'x': 0,
         'y': 150,
         'opacity': 1,
         'stroke': '#888',
         'strokeWidth': 1,
         'x2': 200},
        {'x': 0,
         'y': 100,
         'opacity': 1,
         'stroke': '#888',
         'strokeWidth': 1,
         'x2': 200},
        {'x': 0,
         'y': 50,
         'opacity': 1,
         'stroke': '#888',
         'strokeWidth': 1,
         'x2': 200},
        {'x': 0,
         'y': 0,
         'opacity': 1,
         'stroke': '#888',
         'strokeWidth': 1,
         'x2': 200}],
       'zindex': 0}],
     'x': 0.5,
     'y': 0.5,
     'orient': 'left'}],
   'zindex': 0,
   'aria': False},
  {'marktype': 'group',
   'role': 'axis',
   'interactive': False,
   'clip': False,
   'items': [{'items': [{'marktype': 'rule',
       'role': 'axis-tick',
       'interactive': False,
       'clip': False,
       'items': [{'x': 0,
         'y': 0,
         'opacity': 1,
         'stroke': '#fff',
         'strokeWidth': 1,
         'y2': 5},
        {'x': 53,
         'y': 0,
         'opacity': 1,
         'stroke': '#fff',
         'strokeWidth': 1,
         'y2': 5},
        {'x': 105,
         'y': 0,
         'opacity': 1,
         'stroke': '#fff',
         'strokeWidth': 1,
         'y2': 5},
        {'x': 158,
         'y': 0,
         'opacity': 1,
         'stroke': '#fff',
         'strokeWidth': 1,
         'y2': 5}],
       'zindex': 0},
      {'marktype': 'text',
       'role': 'axis-label',
       'interactive': False,
       'clip': False,
       'items': [{'x': 0.0060038424591730005,
         'y': 7,
         'align': 'right',
         'baseline': 'top',
         'fill': '#fff',
         'opacity': 1,
         'text': '2000',
         'angle': 330,
         'limit': 180,
         'font': 'sans-serif',
         'fontSize': 10},
        {'x': 52.65730067243035,
         'y': 7,
         'align': 'right',
         'baseline': 'top',
         'fill': '#fff',
         'opacity': 1,
         'text': '2005',
         'angle': 330,
         'limit': 180,
         'font': 'sans-serif',
         'fontSize': 10},
        {'x': 105.27977905859751,
         'y': 7,
         'align': 'right',
         'baseline': 'top',
         'fill': '#fff',
         'opacity': 1,
         'text': '2010',
         'angle': 330,
         'limit': 180,
         'font': 'sans-serif',
         'fontSize': 10},
        {'x': 157.90225744476464,
         'y': 7,
         'align': 'right',
         'baseline': 'top',
         'fill': '#fff',
         'opacity': 1,
         'text': '2015',
         'angle': 330,
         'limit': 180,
         'font': 'sans-serif',
         'fontSize': 10}],
       'zindex': 0},
      {'marktype': 'rule',
       'role': 'axis-domain',
       'interactive': False,
       'clip': False,
       'items': [{'x': 0,
         'y': 0,
         'opacity': 1,
         'stroke': '#fff',
         'strokeWidth': 1,
         'x2': 200}],
       'zindex': 0},
      {'marktype': 'text',
       'role': 'axis-title',
       'interactive': False,
       'clip': False,
       'items': [{'x': 100,
         'y': 31.6602540378444,
         'align': 'center',
         'baseline': 'top',
         'fill': '#fff',
         'opacity': 1,
         'text': 'Year',
         'angle': 0,
         'font': 'sans-serif',
         'fontSize': 11,
         'fontWeight': 'bold'}],
       'zindex': 0}],
     'x': 0.5,
     'y': 200.5,
     'orient': 'bottom'}],
   'zindex': 0},
  {'marktype': 'group',
   'role': 'axis',
   'interactive': False,
   'clip': False,
   'items': [{'items': [{'marktype': 'rule',
       'role': 'axis-tick',
       'interactive': False,
       'clip': False,
       'items': [{'x': 0,
         'y': 200,
         'opacity': 1,
         'stroke': '#fff',
         'strokeWidth': 1,
         'x2': -5},
        {'x': 0,
         'y': 150,
         'opacity': 1,
         'stroke': '#fff',
         'strokeWidth': 1,
         'x2': -5},
        {'x': 0,
         'y': 100,
         'opacity': 1,
         'stroke': '#fff',
         'strokeWidth': 1,
         'x2': -5},
        {'x': 0,
         'y': 50,
         'opacity': 1,
         'stroke': '#fff',
         'strokeWidth': 1,
         'x2': -5},
        {'x': 0,
         'y': 0,
         'opacity': 1,
         'stroke': '#fff',
         'strokeWidth': 1,
         'x2': -5}],
       'zindex': 0},
      {'marktype': 'text',
       'role': 'axis-label',
       'interactive': False,
       'clip': False,
       'items': [{'x': -7,
         'y': 200,
         'align': 'right',
         'baseline': 'middle',
         'fill': '#fff',
         'opacity': 1,
         'text': '0',
         'angle': 0,
         'limit': 180,
         'font': 'sans-serif',
         'fontSize': 10},
        {'x': -7,
         'y': 150,
         'align': 'right',
         'baseline': 'middle',
         'fill': '#fff',
         'opacity': 1,
         'text': '20',
         'angle': 0,
         'limit': 180,
         'font': 'sans-serif',
         'fontSize': 10},
        {'x': -7,
         'y': 100,
         'align': 'right',
         'baseline': 'middle',
         'fill': '#fff',
         'opacity': 1,
         'text': '40',
         'angle': 0,
         'limit': 180,
         'font': 'sans-serif',
         'fontSize': 10},
        {'x': -7,
         'y': 50,
         'align': 'right',
         'baseline': 'middle',
         'fill': '#fff',
         'opacity': 1,
         'text': '60',
         'angle': 0,
         'limit': 180,
         'font': 'sans-serif',
         'fontSize': 10},
        {'x': -7,
         'y': 0,
         'align': 'right',
         'baseline': 'middle',
         'fill': '#fff',
         'opacity': 1,
         'text': '80',
         'angle': 0,
         'limit': 180,
         'font': 'sans-serif',
         'fontSize': 10}],
       'zindex': 0},
      {'marktype': 'rule',
       'role': 'axis-domain',
       'interactive': False,
       'clip': False,
       'items': [{'x': 0,
         'y': 200,
         'opacity': 1,
         'stroke': '#fff',
         'strokeWidth': 1,
         'y2': 0}],
       'zindex': 0},
      {'marktype': 'text',
       'role': 'axis-title',
       'interactive': False,
       'clip': False,
       'items': [{'x': -23,
         'y': 100,
         'align': 'center',
         'baseline': 'bottom',
         'fill': '#fff',
         'opacity': 1,
         'text': 'Real GDP in billion U.S. dollars',
         'angle': -90,
         'font': 'sans-serif',
         'fontSize': 11,
         'fontWeight': 'bold'}],
       'zindex': 0}],
     'x': 0.5,
     'y': 0.5,
     'orient': 'left'}],
   'zindex': 0},
  {'marktype': 'line',
   'name': 'marks',
   'role': 'mark',
   'interactive': True,
   'clip': False,
   'items': [{'x': 0,
     'y': 44.875,
     'stroke': '#666666',
     'strokeWidth': 2,
     'defined': True,
     'description': 'Year: Dec 31, 1999; Real GDP in billion U.S. dollars: 62.05'},
    {'x': 10.547550432276658,
     'y': 44.95,
     'stroke': '#666666',
     'strokeWidth': 2,
     'defined': True,
     'description': 'Year: Dec 31, 2000; Real GDP in billion U.S. dollars: 62.02'},
    {'x': 21.06628242074928,
     'y': 42.97499999999999,
     'stroke': '#666666',
     'strokeWidth': 2,
     'defined': True,
     'description': 'Year: Dec 31, 2001; Real GDP in billion U.S. dollars: 62.81'},
    {'x': 31.585014409221902,
     'y': 42.899999999999984,
     'stroke': '#666666',
     'strokeWidth': 2,
     'defined': True,
     'description': 'Year: Dec 31, 2002; Real GDP in billion U.S. dollars: 62.84'},
    {'x': 42.10374639769452,
     'y': 40.7,
     'stroke': '#666666',
     'strokeWidth': 2,
     'defined': True,
     'description': 'Year: Dec 31, 2003; Real GDP in billion U.S. dollars: 63.72'},
    {'x': 52.65129682997119,
     'y': 36.12500000000001,
     'stroke': '#666666',
     'strokeWidth': 2,
     'defined': True,
     'description': 'Year: Dec 31, 2004; Real GDP in billion U.S. dollars: 65.55'},
    {'x': 63.170028818443804,
     'y': 33.9,
     'stroke': '#666666',
     'strokeWidth': 2,
     'defined': True,
     'description': 'Year: Dec 31, 2005; Real GDP in billion U.S. dollars: 66.44'},
    {'x': 73.68876080691643,
     'y': 33.70000000000002,
     'stroke': '#666666',
     'strokeWidth': 2,
     'defined': True,
     'description': 'Year: Dec 31, 2006; Real GDP in billion U.S. dollars: 66.52'},
    {'x': 84.20749279538904,
     'y': 30.275000000000006,
     'stroke': '#666666',
     'strokeWidth': 2,
     'defined': True,
     'description': 'Year: Dec 31, 2007; Real GDP in billion U.S. dollars: 67.89'},
    {'x': 94.75504322766571,
     'y': 31.099999999999994,
     'stroke': '#666666',
     'strokeWidth': 2,
     'defined': True,
     'description': 'Year: Dec 31, 2008; Real GDP in billion U.S. dollars: 67.56'},
    {'x': 105.27377521613832,
     'y': 28.900000000000013,
     'stroke': '#666666',
     'strokeWidth': 2,
     'defined': True,
     'description': 'Year: Dec 31, 2009; Real GDP in billion U.S. dollars: 68.44'},
    {'x': 115.79250720461096,
     'y': 25.850000000000016,
     'stroke': '#666666',
     'strokeWidth': 2,
     'defined': True,
     'description': 'Year: Dec 31, 2010; Real GDP in billion U.S. dollars: 69.66'},
    {'x': 126.31123919308358,
     'y': 26.49999999999999,
     'stroke': '#666666',
     'strokeWidth': 2,
     'defined': True,
     'description': 'Year: Dec 31, 2011; Real GDP in billion U.S. dollars: 69.4'},
    {'x': 136.85878962536023,
     'y': 24.6,
     'stroke': '#666666',
     'strokeWidth': 2,
     'defined': True,
     'description': 'Year: Dec 31, 2012; Real GDP in billion U.S. dollars: 70.16'},
    {'x': 147.37752161383287,
     'y': 25.324999999999996,
     'stroke': '#666666',
     'strokeWidth': 2,
     'defined': True,
     'description': 'Year: Dec 31, 2013; Real GDP in billion U.S. dollars: 69.87'},
    {'x': 157.89625360230548,
     'y': 25.59999999999998,
     'stroke': '#666666',
     'strokeWidth': 2,
     'defined': True,
     'description': 'Year: Dec 31, 2014; Real GDP in billion U.S. dollars: 69.76'},
    {'x': 168.4149855907781,
     'y': 27.749999999999986,
     'stroke': '#666666',
     'strokeWidth': 2,
     'defined': True,
     'description': 'Year: Dec 31, 2015; Real GDP in billion U.S. dollars: 68.9'},
    {'x': 178.96253602305475,
     'y': 25.249999999999993,
     'stroke': '#666666',
     'strokeWidth': 2,
     'defined': True,
     'description': 'Year: Dec 31, 2016; Real GDP in billion U.S. dollars: 69.9'},
    {'x': 189.4812680115274,
     'y': 21.299999999999986,
     'stroke': '#666666',
     'strokeWidth': 2,
     'defined': True,
     'description': 'Year: Dec 31, 2017; Real GDP in billion U.S. dollars: 71.48'},
    {'x': 200,
     'y': 19.600000000000016,
     'stroke': '#666666',
     'strokeWidth': 2,
     'defined': True,
     'description': 'Year: Dec 31, 2018; Real GDP in billion U.S. dollars: 72.16'}],
   'zindex': 0},
  {'marktype': 'group',
   'role': 'title',
   'interactive': False,
   'clip': False,
   'items': [{'items': [{'marktype': 'text',
       'role': 'title-text',
       'interactive': False,
       'clip': False,
       'items': [{'align': 'center',
         'baseline': 'top',
         'fill': '#fff',
         'opacity': 1,
         'text': ['Real Gross Domestic Product (GDP) of the',
          'federal state of West Virginia from 2000',
          'to 2019 (in billion U.S. dollars)'],
         'angle': 0,
         'font': 'sans-serif',
         'fontSize': 13,
         'fontWeight': 'bold'}],
       'zindex': 0}],
     'x': 100,
     'y': -52,
     'align': 'center',
     'orient': 'top',
     'angle': 0}],
   'zindex': 0}],
 'x': 0,
 'y': 0,
 'width': 200,
 'height': 200,
 'fill': 'transparent',
 'stroke': '#ddd'}

In [19]:
# try out specs
with open(data_dir + 'vl_spec/' + str(n) + '.vl.json', 'r') as f:
    df_vl = json.load(f)

In [20]:
df_vl

{'config': {'background': '#333',
  'title': {'color': '#fff', 'subtitleColor': '#fff'},
  'style': {'guide-label': {'fill': '#fff'}, 'guide-title': {'fill': '#fff'}},
  'axis': {'domainColor': '#fff', 'gridColor': '#888', 'tickColor': '#fff'},
  'range': {'category': ['#1b9e77',
    '#d95f02',
    '#7570b3',
    '#e7298a',
    '#66a61e',
    '#e6ab02',
    '#a6761d',
    '#666666']}},
 'data': {'url': 'data/12454.tsv'},
 'mark': 'line',
 'encoding': {'color': {'value': '#666666'},
  'x': {'type': 'temporal',
   'axis': {'labelAngle': -30},
   'bin': False,
   'field': 'Year'},
  'y': {'type': 'quantitative',
   'axis': {'title': 'Real GDP in billion U.S. dollars'},
   'field': 'Real GDP in billion U\\.S\\. dollars'}},
 'title': ['Real Gross Domestic Product (GDP) of the',
  'federal state of West Virginia from 2000',
  'to 2019 (in billion U.S. dollars)'],
 '$schema': 'https://vega.github.io/schema/vega-lite/v4.8.1.json'}

In [14]:
!ls /Users/jnaiman/Downloads/tmp/JCDL2025/other_datasets/vistext/data/README.md

/Users/jnaiman/Downloads/tmp/JCDL2025/other_datasets/vistext/data/README.md

## Dataset pre processing?

Trying out some of: https://github.com/mitvis/vistext/blob/main/code/dataset_generation.ipynb

In [24]:
import random
import os
from PIL import Image
import json
from tqdm import tqdm
import time
import pickle
import pandas as pd
from sklearn.model_selection import train_test_split

#import utils_gen
from utils import utils_gen
pd.set_option('display.max_colwidth', None)

In [25]:
seed = 2022
random.seed(seed)

debug = False
save_gen = True

In [26]:
path_scenegraph = data_dir + "/scenegraphs"
path_L2L3 = data_dir + "/L2L3_captions.json"

In [27]:
data_L1 = []
n_success = 0
n_error = 0

files_sg = list(filter(lambda k: 'json' in k, os.listdir(path_scenegraph)))
files_sg.sort()

assert(len(files_sg) == 8822) ## unit test check length

for file in tqdm(files_sg):
    filepath = os.path.join(path_scenegraph, file)
    with open(filepath) as f:
        read_sg = json.load(f)
        try:
            parsed_sg = utils_gen.parse_all_sg(read_sg)
            parsed_dt = utils_gen.parse_all_dt(read_sg)
            parsed_metadata = utils_gen.parse_all_sg(read_sg,src=False)
            parsed_caption, parsed_metadatadict = utils_gen.generate_caption(*parsed_metadata)
            data_L1.append((file.replace(".json",""), parsed_sg, parsed_dt, parsed_caption, parsed_metadata))
            if debug:
                print(f"Parsed Scenegraph: {parsed_sg}\n")
                print(f"Parsed Datatable: {parsed_dt}\n")
                print(f"Parsed L1 Metadata: {parsed_metadata}")
                display(Image.open(os.path.join("../data/images", file.replace(".json",".png"))))
                print(f"Parsed Caption: {parsed_caption}")
            n_success += 1
        except Exception as e:
            n_error += 1
            print(e)
print(f"Successes: {n_success}")
print(f"Errors: {n_error}")

100%|██████████| 8822/8822 [00:08<00:00, 1005.67it/s]

Successes: 8822
Errors: 0

In [28]:
df_L1 = pd.DataFrame(data_L1, columns=["img_id", "scenegraph", "datatable", "caption_L1", "L1_properties"])
df_L1["img_id"] = pd.to_numeric(df_L1["img_id"])

In [29]:
## unit test
for r in df_L1.sample(n=5).itertuples():
    assert(all(r[5][0] in s for s in [r[2], r[4]])==True) ## check chart type
    assert(all(r[5][1] in s for s in [r[2], r[3], r[4]])==True) ## check chart title
    assert(all(r[5][2] in s for s in [r[2], r[3], r[4]])==True) ## check x-axis
    assert(all(r[5][3] in s for s in [r[2], r[3], r[4]])==True) ## check y-axis

In [34]:
r[5]

['area',
 'Cuba : Total population from 2009 to 2019 (in million inhabitants)',
 'Year',
 'Inhabitants in millions',
 'linear scale of range 2010 to 2018',
 'linear scale with a minimum of 0 and a maximum of 12']

In [37]:
graph_types = []
for i in range(len(df_L1)):
    d = df_L1.iloc[i]
    gi = d['L1_properties']
    # chart type
    graph_types.append(gi[0])
graph_types = np.unique(graph_types)
graph_types

array(['area', 'bar', 'line'], dtype='<U4')

In [ ]:
xaxis_bar = []
#ilocs_linear = []
for i in range(len(df_L1)):
    d = df_L1.iloc[i]
    gi = d['L1_properties']
    if gi[0] == 'bar':
        xax = gi[-2].split('scale')[0].rstrip().lstrip()
        xaxis_bar.append(xax)
        # if 'linear' in xax:
        #     ilocs_linear.append(i)

xaxis_bar = np.unique(xaxis_bar)
xaxis_bar

array(['', 'categorical', 'linear'], dtype='<U11')

In [44]:
ilocs_linear = []
for i in range(len(df_L1)):
    d = df_L1.iloc[i]
    gi = d['L1_properties']
    if gi[0] == 'bar':
        xax = gi[-2].split('scale')[0].rstrip().lstrip()
        yax = gi[-1].split('scale')[0].rstrip().lstrip()
        if 'linear' in xax and 'linear' in yax:
            ilocs_linear.append(i)

In [45]:
df_L1.iloc[ilocs_linear]

,img_id,scenegraph,datatable,caption_L1,L1_properties
152,1135,title Number of hospitals in Estonia from 2000 to 2018 x 190 y -37 x-axis x 190 y 40 Year y-axis x -23 y 100 Number of hospitals xtick x 10 val 2000 x 30 val 2001 x 50 val 2002 x 70 val 2003 x 90 val 2004 x 110 val 2005 x 130 val 2006 x 150 val 2007 x 170 val 2008 x 190 val 2009 x 210 val 2010 x 230 val 2011 x 250 val 2012 x 270 val 2013* x 290 val 2014 x 310 val 2015 x 330 val 2016 x 350 val 2017 x 370 val 2018 ytick y 200 val 0 y 171 val 10 y 143 val 20 y 114 val 30 y 86 val 40 y 57 val 50 y 29 val 60 y 0 val 70 marks bar XY 361 114.286 width 18 H 85.714 desc XY 341 114.286 width 18 H 85.714 desc XY 321 114.286 width 18 H 85.714 desc XY 301 114.286 width 18 H 85.714 desc XY 281 114.286 width 18 H 85.714 desc XY 261 111.429 width 18 H 88.571 desc XY 241 40.0 width 18 H 160 desc XY 221 42.857 width 18 H 157.143 desc XY 201 37.143 width 18 H 162.857 desc XY 181 37.143 width 18 H 162.857 desc XY 161 34.286 width 18 H 165.714 desc XY 141 42.857 width 18 H 157.143 desc XY 121 45.714 width 18 H 154.286 desc XY 101 48.571 width 18 H 151.429 desc XY 81 57.143 width 18 H 142.857 desc XY 61 62.857 width 18 H 137.143 desc XY 41 54.286 width 18 H 145.714 desc XY 21 8.571 width 18 H 191.429 desc XY 1 5.714 width 18 H 194.286 desc,Number of hospitals in Estonia from 2000 to 2018 <s> Year Number of hospitals 2018 30 2017 30 2016 30 2015 30 2014 30 2013* 31 2012 56 2011 55 2010 57 2009 57 2008 58 2007 55 2006 54 2005 53 2004 50 2003 48 2002 51 2001 67 2000 68,Here a is a bar diagram called Number of hospitals in Estonia from 2000 to 2018. The x-axis shows Year while the y-axis shows Number of hospitals.,"[bar, Number of hospitals in Estonia from 2000 to 2018, Year, Number of hospitals, linear scale with a minimum of 2000 and a maximum of 2018, linear scale with a minimum of 0 and a maximum of 70]"
159,1141,title Share of households with internet access in Sweden from 2007 to 2019 x -35.5 y -65 x-axis x 130 y 48.579 Response y-axis x 18 y -10 Share of households xtick x 9.5 val 2007 x 29.5 val 2008 x 49.5 val 2009 x 69.5 val 2010 x 89.5 val 2011 x 109.5 val 2012 x 129.5 val 2013 x 149.5 val 2014 x 169.5 val 2015 x 189.5 val 2016* x 209.5 val 2017 x 229.5 val 2018 x 249.5 val 2019 ytick y 0 val 0.0 y 39.99999999999999 val 0.2 y 80 val 0.4 y 120 val 0.6 y 160 val 0.8 y 200 val 1.0 marks bar XY 241 8.0 width 18 H 192 desc XY 221 16.0 width 18 H 184 desc XY 201 10.0 width 18 H 190 desc XY 181 12.0 width 18 H 188 desc XY 161 18.0 width 18 H 182 desc XY 141 20.0 width 18 H 180 desc XY 121 14.0 width 18 H 186 desc XY 101 16.0 width 18 H 184 desc XY 81 18.0 width 18 H 182 desc XY 61 24 width 18 H 176 desc XY 41 28.0 width 18 H 172 desc XY 21 32.0 width 18 H 168 desc XY 1 42.0 width 18 H 158 desc,Share of households with internet access in Sweden from 2007 to 2019 <s> Response Share of households 2019 0.96 2018 0.92 2017 0.95 2016* 0.94 2015 0.91 2014 0.9 2013 0.93 2012 0.92 2011 0.91 2010 0.88 2009 0.86 2008 0.84 2007 0.79,"Here a bar diagram is titled Share of households with internet access in Sweden from 2007 to 2019. A linear scale with a minimum of 0.0 and a maximum of 1.0 can be found along the y-axis, marked Share of households. There is a linear scale from 2007 to 2019 on the x-axis, labeled Response.","[bar, Share of households with internet access in Sweden from 2007 to 2019, Response, Share of households, linear scale from 2007 to 2019, linear scale with a minimum of 0.0 and a maximum of 1.0]"
306,1274,"title Total number of companies in France between 2008 and 2017 x -67.258 y -40.5 x-axis x 100 y 49 Year y-axis x -54.258 y 100 Number of enterprises xtick x 10 val 2008 x 30 val 2009 x 50 val 2010 x 70 val 2011 x 90 val 2012 x 110 val 2013 x 130 val 2014* x 150 val 2015* x 170 val 2016 x 190 val 2017 ytick y 200 val 0 y 171 val 500,000 y 143 val 1,000,000 y 114 val 1,500,000 y 86 val 2,000,000 y 57 val 2,500,000 y 29 val 3,000,000 y 0 val 3,500,000 marks bar XY 181 40.915 width 18 H 159.085 desc XY 161 25.245 width 18 H 174.755 desc XY 141 33.782 width 18 H 166.218 desc XY 121 17.821 width 18 H 182.179 desc XY 101 27.617 width 18 H 172.383 desc XY 81 35.29 width 18 H 164.71 desc XY 61 53.29 width 18 H 146.71 desc XY 41 56.361 width 18 H 143.639 desc XY 21 74.684 width 18 H 125.316 desc XY 1 65.038 width 18 H 134.962 desc",Total number of companies in France between 2008 and 2017 <s> Year Number of enterprises 2017 2783993 2016 3058220 2015* 2908814 2014* 3188138 2013 3016704 2012 2882419 2011 2567431 2010 2513679 2009 2193030 2008 2361827,Here a is a bar diagram named Total number of companies in France between 2008 and 2017. Year is shown along a linear scale of range 2008 to 2017 along the x-axis. Number of enterprises is defined along the y-axis.,"[bar, Total number of companies in France between 2008 and 2017, Year, Number of enterprises, linear scale of range 2008 to 2017, linear scale from 0 to 3,500,000]"
489,1439,title Apparent steel consumption per capita in Mexico from 2003 to 2018 (in kilograms of finished steel products) x 160 y -47 x-axis x 160 y 40 Year y-axis x -29 y 100 Per capita use in kilograms xtick x 10 val 2003 x 30 val 2004 x 50 val 2005 x 70 val 2006 x 90 val 2007 x 110 val 2008 x 130 val 2009 x 150 val 2010 x 170 val 2011 x 190 val 2012* x 210 val 2013 x 230 val 2014 x 250 val 2015 x 270 val 2016 x 290 val 2017 x 310 val 2018 ytick y 200 val 0 y 155 val 50 y 109 val 100 y 64 val 150 y 18 val 200 marks bar XY 301 23.273 width 18 H 176.727 desc XY 281 13.818 width 18 H 186.182 desc XY 261 18.364 width 18 H 181.636 desc XY 241 20.364 width 18 H 179.636 desc XY 221 28.182 width 18 H 171.818 desc XY 201 47.364 width 18 H 152.636 desc XY 181 42.636 width 18 H 157.364 desc XY 161 48.818 width 18 H 151.182 desc XY 141 63.909 width 18 H 136.091 desc XY 121 81.909 width 18 H 118.091 desc XY 101 59.727 width 18 H 140.273 desc XY 81 50.909 width 18 H 149.091 desc XY 61 55.545 width 18 H 144.455 desc XY 41 69.182 width 18 H 130.818 desc XY 21 61.273 width 18 H 138.727 desc XY 1 69.091 width 18 H 130.909 desc,Apparent steel consumption per capita in Mexico from 2003 to 2018 (in kilograms of finished steel products) <s> Year Per capita use in kilograms 2018 194.4 2017 204.8 2016 199.8 2015 197.6 2014 189 2013 167.9 2012* 173.1 2011 166.3 2010 149.7 2009 129.9 2008 154.3 2007 164 2006 158.9 2005 143.9 2004 152.6 2003 144,"Here a is a bar diagram called Apparent steel consumption per capita in Mexico from 2003 to 2018 (in kilograms of finished steel products). A linear scale from 2003 to 2018 can be seen along the x-axis, marked Year. A linear scale from 0 to 200 can be found on the y-axis, labeled Per capita use in kilograms.","[bar, Apparent steel consumption per capita in Mexico from 2003 to 2018 (in kilograms of finished steel products), Year, Per capita use in kilograms, linear scale from 2003 to 2018, linear scale from 0 to 200]"
593,1532,"title Number of general practitioners employed in the United Kingdom (UK) from 2000 to 2019 x -68 y -34 x-axis x 200 y 39.526 Year y-axis x -55 y 100 Number of employees xtick x 10 val 2000 x 30 val 2001 x 50 val 2002 x 70 val 2003 x 90 val 2004 x 110 val 2005 x 130 val 2006 x 150 val 2007 x 170 val 2008 x 190 val 2009 x 210 val 2010 x 230 val 2011 x 250 val 2012 x 270 val 2013 x 290 val 2014 x 310 val 2015* x 330 val 2016 x 350 val 2017 x 370 val 2018 x 390 val 2019 ytick y 200 val 0 y 164 val 10,000 y 127 val 20,000 y 91 val 30,000 y 55 val 40,000 y 18 val 50,000 marks bar XY 381 14.196 width 18 H 185.804 desc XY 361 19.749 width 18 H 180.251 desc XY 341 18.822 width 18 H 181.178 desc XY 321 17.891 width 18 H 182.109 desc XY 301 17.567 width 18 H 182.433 desc XY 281 16.018 width 18 H 183.982 desc XY 261 18.636 width 18 H 181.364 desc XY 241 18.153 width 18 H 181.847 desc XY 221 18.771 width 18 H 181.229 desc XY 201 23.124 width 18 H 176.876 desc XY 181 20.229 width 18 H 179.771 desc XY 161 29.636 width 18 H 170.364 desc XY 141 35.047 width 18 H 164.953 desc XY 121 37.924 width 18 H 162.076 desc XY 101 39.276 width 18 H 160.724 desc XY 81 43.909 width 18 H 156.091 desc XY 61 48.556 width 18 H 151.444 desc XY 41 53.596 width 18 H 146.404 desc XY 21 55.684 width 18 H 144.316 desc XY 1 57.825 width 18 H 142.175 desc",Number of general practitioners employed in the United Kingdom (UK) from 2000 to 2019 <s> Year Number of employees 2019 51096 2018 49569 2017 49824 2016 50080 2015* 50169 2014 50595 2013 49875 2012 50008 2011 49838 2010 48641 2009 49437 2008 46850 2007 45362 2006 44571 2005 44199 2004 42925 2003 41647 2002 40261 2001 39687 2000 39098,Here a is a bar chart labeled Number of general practitioners employed in the United Kingdom (UK) from 2000 to 2019. The y-axis plots Number of employees while the x-axis plots Year.,"[bar, Number of general practitioners employed in the United Kingdom (UK) from 2000 to 2019, Year, Number of employees, linear scale of range 2000 to 2019, linear scale of range 0 to 50,000]"
...,...,...,...,...,...
8038,8233,"title U.S. e-commerce value of drugs and druggists ' sundries wholesale trade from 2006 to 2018 (in million U.S. dollars) x 100 y -47 x-axis x 100 y 35 Year y-axis x -50 y 100 E-commerce xtick x 10 val 2006 x 30 val 2007 x 50 val 2008 x 70 val 2009 x 90 val 2010 x 110 val 2011 x 130 val 2012 x 150 val 2013 x 170 val 2014 x 190 val 2015 ytick y 200 val 0 y 169 val 100,000 y 138 val 200,000 y 108 val 300,000 y 77 val 400,000 y 46 val 500,000 y 15 val 600,000 marks bar XY 181 11.098 width 18 H 188.902 desc XY 161 31.565 width 18 H 168.435 desc XY 141 46.82 width 18 H 153.18 desc XY 121 51.817 width 18 H 148.183 desc XY 101 54.813 width 18 H 145.187 desc XY 81 63.551 width 18 H 136.449 desc XY 61 69.72 width 18 H 130.28 desc XY 41 79.728 width 18 H 120.272 desc XY 21 88.687 width 18 H 111.313 desc XY 1 93.914 width 18 H 106.086 desc",U.S. e-commerce value of drugs and druggists ' sundries wholesale trade from 2006 to 2018 (in million U.S. dollars) <s> Year E-commerce 2015 613931 2014 547414 2013 497835 2012 481596 2011 471858 2010 443458 2009 423411 2008 390884 2007 361767 2006 344778,"U.S. e-commerce value of drugs and druggists ' sundries wholesale trade from 2006 to 2018 (in million U.S. dollars) is a bar graph. There is a linear scale of range 0 to 600,000 on the y-axis, marked E-commerce. On the x-axis, Year is drawn on a linear scale from 2006 to 2015.","[bar, U.S. e-commerce value of drugs and druggists ' sundries wholesale trade from 2006 to 2018 (in million U.S. dollars), Year, E-commerce, linear scale from 2006 to 2015, linear scale of range 0 to 600,000]"
8223,840,title Z Holdings Corporation 's net income from fiscal year 2002 to 2019 (in billion Japanese yen) x 180 y -54.5 x-axis x 180 y 40 Year y-axis x -29 y 100 Net income in billion Japanese yen xtick x 10 val 2002 x 30 val 2003 x 50 val 2004 x 70 val 2005 x 90 val 2006 x 110 val 2007 x 130 val 2008 x 150 val 2009 x 170 val 2010 x 190 val 2011 x 210 val 2012 x 230 val 2013* x 250 val 2014 x 270 val 2015 x 290 val 2016 x 310 val 2017 x 330 val 2018 x 350 val 2019 ytick y 200 val 0 y 144 val 50 y 89 val 100 y 33 val 150 marks bar XY 341 102.2 width 18 H 97.8 desc XY 321 113.522 width 18 H 86.478 desc XY 301 50.656 width 18 H 149.344 desc XY 281 52.633 width 18 H 147.367 desc XY 261 8.344 width 18 H 191.656 desc XY 241 51.189 width 18 H 148.811 desc XY 221 55.922 width 18 H 144.078 desc XY 201 72.178 width 18 H 127.822 desc XY 181 88.267 width 18 H 111.733 desc XY 161 97.589 width 18 H 102.411 desc XY 141 107.2 width 18 H 92.8 desc XY 121 116.978 width 18 H 83.022 desc XY 101 130.422 width 18 H 69.578 desc XY 81 135.6 width 18 H 64.4 desc XY 61 147.678 width 18 H 52.322 desc XY 41 159.422 width 18 H 40.578 desc XY 21 172.411 width 18 H 27.589 desc XY 1 186.556 width 18 H 13.444 desc,Z Holdings Corporation 's net income from fiscal year 2002 to 2019 (in billion Japanese yen) <s> Year Net income in billion Japanese yen 2019 88.02 2018 77.83 2017 134.41 2016 132.63 2015 172.49 2014 133.93 2013* 129.67 2012 115.04 2011 100.56 2010 92.17 2009 83.52 2008 74.72 2007 62.62 2006 57.96 2005 47.09 2004 36.52 2003 24.83 2002 12.1,"This is a bar chart named Z Holdings Corporation 's net income from fiscal year 2002 to 2019 (in billion Japanese yen). The x-axis plots Year along a linear scale with a minimum of 2002 and a maximum of 2019. There is a linear scale from 0 to 150 on the y-axis, marked Net income in billion Japanese yen.","[bar, Z Holdings Corporation 's net income from fiscal year 2002 to 2019 (in billion Japanese yen), Year, Net income in billion Japanese yen, linear scale with a minimum of 2002 and a maximum of 2019, linear scale from 0 to 150]"
8378,854,"title Number of auto thefts per 100,000 vehicles in Brazil from 2007 to 2018 x -67 y -70 x-axis x 100 y 43.799 Auto thefts per 100,000 vehicles y-axis x -53 y 120 Year xtick x 0 val 0 x 33 val 50 x 67 val 100 x 100 val 150 x 133 val 200 x 167 val 250 x 200 val 300 ytick y 10 val 2007 y 30 val 2008 y 50 val 2009 y 70 val 2010 y 90 val 2011 y 110 val 2012 y 130 val 2013 y 150 val 2014 y 170 val 2015 y 190 val 2016 y 210 val 2017* y 230 val 2018 marks bar XY 0 221 width 163.533 H 18 desc XY 0 201 width 195 H 18 desc XY 0 181 width 194.053 H 18 desc XY 0 161 width 179.047 H 18 desc XY 0 141 width 186.64 H 18 desc XY 0 121 width 178.1 H 18 desc XY 0 101 width 177.307 H 18 desc XY 0 81 width 162.233 H 18 desc XY 0 61 width 156.007 H 18 desc XY 0 41 width 175.833 H 18 desc XY 0 21 width 178.707 H 18 desc XY 0 1 width 158.053 H 18 desc","Number of auto thefts per 100,000 vehicles in Brazil from 2007 to 2018 <s> Auto thefts per 100,000 vehicles Year 245.3 2018 292.5 2017* 291.08 2016 268.57 2015 279.96 2014 267.15 2013 265.96 2012 243.35 2011 234.01 2010 263.75 2009 268.06 2008 237.08 2007","Here a bar graph is titled Number of auto thefts per 100,000 vehicles in Brazil from 2007 to 2018. A linear scale from 0 to 300 can be found on the x-axis, marked Auto thefts per 100,000 vehicles. Year is defined along the y-axis.","[bar, Number of auto thefts per 100,000 vehicles in Brazil from 2007 to 2018, Auto thefts per 100,000 vehicles, Year, linear scale from 0 to 300, linear scale with a minimum of 2007 and a maximum of 2018]"
8462,8615,"title U.S. e-commerce value of computers , computer equipment and software wholesale trade from 2007 to 2018 (in million U.S. dollars) x -45 y -98 x-axis x 100 y 22.5 Total y-axis x -45 y -11 Year xtick x 0 val 0 x 36 val 50,000 x 71 val 100,000 x 107 val 150,000 x 143 val 200,000 x 179 val 250,000 ytick y 10 val 2007 y 30 val 2008 y 50 val 2009 y 70 val 2010 y 90 val 2011* y 110 val 2012* y 130 val 2013 y 150 val 2014 y 170 val 2015 y 190 val 2016 y 210 val 2017 y 230 val 2018 marks bar XY 0 221 width 194.976 H 18 desc XY 0 201 width 180.418 H 18 desc XY 0 181 width 173.328 H 18 desc XY 0 161 width 173.876 H 18 desc XY 0 141 width 172.149 H 18 desc XY 0 121 width 169.462 H 18 desc XY 0 101 width 165.776 H 18 desc XY 0 81 width 169.439 H 18 desc XY 0 61 width 174.994 H 18 desc XY 0 41 width 161.61 H 18 desc XY 0 21 width 176.893 H 18 desc XY 0 1 width 180.925 H 18 desc","U.S. e-commerce value of computers , computer equipment and software wholesale trade from 2007 to 2018 (in million U.S. dollars) <s> Total Year 272967 2018 252585 2017 242659 2016 243427 2015 241009 2014 237247 2013 232087 2012* 237215 2011* 244991 2010 226254 2009 247650 2008 253295 2007","Here a bar diagram is labeled U.S. e-commerce value of computers , computer equipment and software wholesale trade from 2007 to 2018 (in million U.S. dollars). Total is measured as a linear scale from 0 to 250,000 on the x-axis. Along the y-axis, Year is plotted.","[bar, U.S. e-commerce value of computers , computer equipment and software wholesale trade from 2007 to 2018 (in million U.S. dollars), Total, Year, linear scale from 0 to 250,000, linear scale from 2007 to 2018]"
8746,930,"title Annual sales revenue of John Lewis in the United Kingdom (UK) from 2009 to 2020 (in million GBP) x 100 y -47 x-axis x 100 y 39.833 Revenue in million GBP y-axis x -47.67 y 120 Year xtick x 0 val 0 x 50 val 1,000 x 100 val 2,000 x 150 val 3,000 x 200 val 4,000 ytick y 10 val 2009 y 30 val 2010 y 50 val 2011 y 70 val 2012 y 90 val 2013 y 110 val 2014 y 130 val 2015** y 150 val 2016 y 170 val 2017 y 190 val 2018 y 210 val 2019 y 230 val 2020 marks bar XY 0 221 width 189.08 H 18 desc XY 0 201 width 194.36 H 18 desc XY 0 181 width 198.055 H 18 desc XY 0 161 width 189.035 H 18 desc XY 0 141 width 183.14 H 18 desc XY 0 121 width 178.285 H 18 desc XY 0 101 width 163.705 H 18 desc XY 0 81 width 152.47 H 18 desc XY 0 61 width 134.315 H 18 desc XY 0 41 width 133.095 H 18 desc XY 0 21 width 120.87 H 18 desc XY 0 1 width 116.355 H 18 desc",Annual sales revenue of John Lewis in the United Kingdom (UK) from 2009 to 2020 (in million GBP) <s> Revenue in million GBP Year 3781.6 2020 3887.2 2019 3961.1 2018 3780.7 2017 3662.8 2016 3565.7 2015** 3274.1 2014 3049.4 2013 2686.3 2012 2661.9 2011 2417.4 2010 2327.1 2009,Annual sales revenue of John Lewis in the United Kingdom (UK) from 2009 to 2020 (in million GBP) is a bar diagram. The y-axis shows Year while the x-axis shows Revenue in million GBP.,"[bar, Annual sales revenue of John Lewis in the United Kingdom (UK) from 2009 to 2020 (in million GBP), Revenue in million GBP, Year, linear scale of range 0 to 4,000, linear scale with a minimum of 2009 and a maximum of 2020]"

In [38]:
df_L1.head()

,img_id,scenegraph,datatable,caption_L1,L1_properties
0,1,title National Football League average ticket price from 2006 to 2019 (in U.S. dollars) x 100 y -32 x-axis x 100 y 40.042 Year y-axis x -24 y 100 Ticket price in U.S. dollars xtick x 0 val 2006 x 31 val 2008 x 62 val 2010 x 92 val 2012 x 123 val 2014 x 154 val 2016 x 185 val 2018 ytick y 200 val 0 y 164 val 20 y 127 val 40 y 91 val 60 y 55 val 80 y 18 val 100 marks line XY 0 86.582 desc XY 15.375 77.982 desc XY 30.75 68.727 desc XY 46.167 63.655 desc XY 61.542 60.964 desc XY 76.917 59.382 desc XY 92.291 57.491 desc XY 107.709 51.745 desc XY 123.083 46.491 desc XY 138.458 43.945 desc XY 153.833 30.945 desc XY 184.625 17.709 desc XY 200 13.909 desc,"National Football League average ticket price from 2006 to 2019 (in U.S. dollars) <s> Year Ticket price in U.S. dollars Dec 31, 2005 62.38 Dec 31, 2006 67.11 Dec 31, 2007 72.2 Dec 31, 2008 74.99 Dec 31, 2009 76.47 Dec 31, 2010 77.34 Dec 31, 2011 78.38 Dec 31, 2012 81.54 Dec 31, 2013 84.43 Dec 31, 2014 85.83 Dec 31, 2015 92.98 Dec 31, 2017 100.26 Dec 31, 2018 102.35","National Football League average ticket price from 2006 to 2019 (in U.S. dollars) is a line chart. There is a linear scale from 2006 to 2018 along the x-axis, marked Year. Along the y-axis, Ticket price in U.S. dollars is measured along a linear scale from 0 to 100.","[line, National Football League average ticket price from 2006 to 2019 (in U.S. dollars), Year, Ticket price in U.S. dollars, linear scale from 2006 to 2018, linear scale from 0 to 100]"
1,10,title Average ticket price Tampa Bay Lightning (NHL) games from 2005/06 to 2014/15 (in U.S. dollars) x -45 y -98 x-axis x 100 y 25 Average ticket price in U.S. dollars y-axis x -45 y -11 Year xtick x 0 val 0 x 44 val 10 x 89 val 20 x 133 val 30 x 178 val 40 ytick y 10 val 05/06 y 30 val 06/07 y 50 val 07/08 y 70 val 08/09 y 90 val 09/10 y 110 val 10/11 y 130 val 11/12 y 150 val 12/13 y 170 val 13/14 y 190 val 14/15 marks bar XY 0 181 width 197.778 H 18 desc XY 0 161 width 187.689 H 18 desc XY 0 141 width 169.422 H 18 desc XY 0 121 width 167.689 H 18 desc XY 0 101 width 167.689 H 18 desc XY 0 81 width 167.689 H 18 desc XY 0 61 width 158.933 H 18 desc XY 0 41 width 188.489 H 18 desc XY 0 21 width 195.289 H 18 desc XY 0 1 width 196.756 H 18 desc,Average ticket price Tampa Bay Lightning (NHL) games from 2005/06 to 2014/15 (in U.S. dollars) <s> Average ticket price in U.S. dollars Year 44.5 14/15 42.23 13/14 38.12 12/13 37.73 11/12 37.73 10/11 37.73 09/10 35.76 08/09 42.41 07/08 43.94 06/07 44.27 05/06,"Here a bar plot is titled Average ticket price Tampa Bay Lightning (NHL) games from 2005/06 to 2014/15 (in U.S. dollars). On the y-axis, Year is defined along a categorical scale starting with 05/06 and ending with 14/15. A linear scale from 0 to 40 can be seen along the x-axis, labeled Average ticket price in U.S. dollars.","[bar, Average ticket price Tampa Bay Lightning (NHL) games from 2005/06 to 2014/15 (in U.S. dollars), Average ticket price in U.S. dollars, Year, linear scale from 0 to 40, categorical scale starting with 05/06 and ending with 14/15]"
2,100,"title Annual number of hospital beds in the United Kingdom (UK) from 2000 to 2019 x 200 y -32 x-axis x 200 y 50 Year y-axis x -50 y 100 Number of beds xtick x 10 val 2000 x 30 val 2001 x 50 val 2002 x 70 val 2003 x 90 val 2004 x 110 val 2005 x 130 val 2006 x 150 val 2007 x 170 val 2008 x 190 val 2009 x 210 val 2010 * x 230 val 2011 x 250 val 2012 x 270 val 2013 x 290 val 2014 x 310 val 2015 x 330 val 2016 x 350 val 2017 x 370 val 2018** x 390 val 2019*** ytick y 200 val 0 y 162 val 50,000 y 123 val 100,000 y 85 val 150,000 y 46 val 200,000 y 8 val 250,000 marks bar XY 381 73.944 width 18 H 126.056 desc XY 361 72.428 width 18 H 127.572 desc XY 341 71.085 width 18 H 128.915 desc XY 321 70.051 width 18 H 129.949 desc XY 301 69.235 width 18 H 130.765 desc XY 281 64.366 width 18 H 135.634 desc XY 261 64.007 width 18 H 135.993 desc XY 241 62.43 width 18 H 137.57 desc XY 221 60.022 width 18 H 139.978 desc XY 201 58.578 width 18 H 141.422 desc XY 181 43.595 width 18 H 156.405 desc XY 161 41.557 width 18 H 158.443 desc XY 141 40.162 width 18 H 159.838 desc XY 121 34.221 width 18 H 165.779 desc XY 101 27.014 width 18 H 172.986 desc XY 81 22.001 width 18 H 177.999 desc XY 61 18.837 width 18 H 181.163 desc XY 41 18.304 width 18 H 181.696 desc XY 21 16.43 width 18 H 183.57 desc XY 1 15.274 width 18 H 184.726 desc",Annual number of hospital beds in the United Kingdom (UK) from 2000 to 2019 <s> Year Number of beds 2019*** 163873 2018** 165844 2017 167589 2016 168934 2015 169995 2014 176324 2013 176791 2012 178841 2011 181972 2010 * 183849 2009 203326 2008 205976 2007 207789 2006 215513 2005 224882 2004 231399 2003 235512 2002 236205 2001 238641 2000 240144,"Annual number of hospital beds in the United Kingdom (UK) from 2000 to 2019 is a bar plot. A linear scale from 0 to 250,000 can be seen on the y-axis, marked Number of beds. A categorical scale from 2000 to 2019*** can be seen on the x-axis, marked Year.","[bar, Annual number of hospital beds in the United Kingdom (UK) from 2000 to 2019, Year, Number of beds, categorical scale from 2000 to 2019***, linear scale from 0 to 250,000]"
3,1000,"title Average monthly salary in public sector in Sweden from 2009 to 2019 (in SEK) x 100 y -37 x-axis x 100 y 35.042 Year y-axis x -44 y 100 Average monthly salary in SEK xtick x 20 val 2010 x 60 val 2012 x 100 val 2014 x 140 val 2016 x 180 val 2018 ytick y 200 val 0 y 171 val 5,000 y 143 val 10,000 y 114 val 15,000 y 86 val 20,000 y 57 val 25,000 y 29 val 30,000 y 0 val 35,000 marks area XY 0 50.286 H 149.714 desc XY 19.989 46.857 H 153.143 desc XY 39.978 44.0 H 156 desc XY 59.967 40.0 H 160 desc XY 80.011 34.857 H 165.143 desc XY 100 29.714 H 170.286 desc XY 119.989 25.143 H 174.857 desc XY 139.978 20.0 H 180 desc XY 160.022 15.429 H 184.571 desc XY 180.011 10.286 H 189.714 desc XY 200 5.714 H 194.286 desc","Average monthly salary in public sector in Sweden from 2009 to 2019 (in SEK) <s> Year Average monthly salary in SEK Dec 31, 2008 26200 Dec 31, 2009 26800 Dec 31, 2010 27300 Dec 31, 2011 28000 Dec 31, 2012 28900 Dec 31, 2013 29800 Dec 31, 2014 30600 Dec 31, 2015 31500 Dec 31, 2016 32300 Dec 31, 2017 33200 Dec 31, 2018 34000","Average monthly salary in public sector in Sweden from 2009 to 2019 (in SEK) is a area diagram. There is a linear scale of range 2010 to 2018 along the x-axis, marked Year. On the y-axis, Average monthly salary in SEK is shown.","[area, Average monthly salary in public sector in Sweden from 2009 to 2019 (in SEK), Year, Average monthly salary in SEK, linear scale of range 2010 to 2018, linear scale of range 0 to 35,000]"
4,1001,title Household penetration rates for dog-ownership in the United States from 1988 to 2016 x 100 y -37 x-axis x 100 y 31.66 Year y-axis x -27.16 y 100 Penetration rates xtick x 14 val 1990 x 50 val 1995 x 86 val 2000 x 121 val 2005 x 157 val 2010 x 193 val 2015 ytick y 200 val 0.0 y 160 val 0.1 y 120 val 0.2 y 80 val 0.3 y 40 val 0.4 y 0 val 0.5 marks area XY 0 52 H 148 desc XY 14.295 48 H 152 desc XY 28.571 48 H 152 desc XY 42.867 56.0 H 144 desc XY 57.143 52 H 148 desc XY 71.438 44.0 H 156 desc XY 85.714 44.0 H 156 desc XY 100.01 44.0 H 156 desc XY 114.286 44.0 H 156 desc XY 128.581 44.0 H 156 desc XY 142.857 17.6 H 182.4 desc XY 157.153 14.8 H 185.2 desc XY 171.429 13.2 H 186.8 desc XY 185.724 24 H 176 desc XY 200 8.0 H 192 desc,"Household penetration rates for dog-ownership in the United States from 1988 to 2016 <s> Year Penetration rates Dec 31, 1987 0.37 Dec 31, 1989 0.38 Dec 31, 1991 0.38 Dec 31, 1993 0.36 Dec 31, 1995 0.37 Dec 31, 1997 0.39 Dec 31, 1999 0.39 Dec 31, 2001 0.39 Dec 31, 2003 0.39 Dec 31, 2005 0.39 Dec 31, 2007 0.456 Dec 31, 2009 0.463 Dec 31, 2011 0.467 Dec 31, 2013 0.44 Dec 31, 2015 0.48",Household penetration rates for dog-ownership in the United States from 1988 to 2016 is a area graph. The x-axis measures Year using linear scale of range 1990 to 2015 while the y-axis plots Penetration rates using linear scale with a minimum of 0.0 and a maximum of 0.5.,"[area, Household penetration rates for dog-ownership in the United States from 1988 to 2016, Year, Penetration rates, linear scale of range 1990 to 2015, linear scale with a minimum of 0.0 and a maximum of 0.5]"